<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Opsional: Kosongkan tabel sebelum seed (hati-hati jika ada relasi)
        // DB::table('products')->truncate();

        $products = [
            [
                'id_produk' => 1,
                'nama_produk' => 'Bibit Cabai',
                'deskripsi' => 'Bibit cabai unggulan siap tanam',
                'harga' => 15000,
                'stok' => 90,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit_cabai.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 07:33:37',
            ],
            [
                'id_produk' => 2,
                'nama_produk' => 'Bibit Semangka',
                'deskripsi' => 'Bibit semangka berkualitas tinggi',
                'harga' => 18000,
                'stok' => 77,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit_semangka.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 07:33:38',
            ],
            [
                'id_produk' => 3,
                'nama_produk' => 'Fungisida',
                'deskripsi' => 'Fungisida untuk mencegah dan mengendalikan jamur tanaman',
                'harga' => 25000,
                'stok' => 55,
                'kategori' => 'Pestisida',
                'gambar_produk' => 'fungisida.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 07:27:37',
            ],
            [
                'id_produk' => 4,
                'nama_produk' => 'Insektisida',
                'deskripsi' => 'Insektisida untuk mengendalikan hama tanaman',
                'harga' => 27000,
                'stok' => 57,
                'kategori' => 'Pestisida',
                'gambar_produk' => 'insektisida.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 07:33:30',
            ],
            [
                'id_produk' => 5,
                'nama_produk' => 'Pupuk NPK',
                'deskripsi' => 'Pupuk NPK untuk pertumbuhan tanaman optimal',
                'harga' => 30000,
                'stok' => 116,
                'kategori' => 'Pupuk',
                'gambar_produk' => 'pupuk_npk.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 07:27:39',
            ],
            [
                'id_produk' => 6,
                'nama_produk' => 'Pupuk Organik',
                'deskripsi' => 'Pupuk organik ramah lingkungan',
                'harga' => 28000,
                'stok' => 97,
                'kategori' => 'Pupuk',
                'gambar_produk' => 'pupuk_organik.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 00:25:15',
            ],
            [
                'id_produk' => 7,
                'nama_produk' => 'Vitamin Buah',
                'deskripsi' => 'Vitamin untuk meningkatkan kualitas buah',
                'harga' => 22000,
                'stok' => 67,
                'kategori' => 'Vitamin',
                'gambar_produk' => 'vitamin_buah.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 07:27:41',
            ],
            [
                'id_produk' => 8,
                'nama_produk' => 'Vitamin Daun',
                'deskripsi' => 'Vitamin untuk kesuburan dan kehijauan daun',
                'harga' => 20000,
                'stok' => 74,
                'kategori' => 'Vitamin',
                'gambar_produk' => 'vitamin_daun.jpg',
                'created_at' => null,
                'updated_at' => '2026-01-07 00:03:00',
            ],
            [
                'id_produk' => 9,
                'nama_produk' => 'Bibit Sawi',
                'deskripsi' => "Bibit sawi unggul adalah pilihan tepat untuk budidaya sayuran yang praktis dan menguntungkan. Bibit ini memiliki tingkat tumbuh yang tinggi, pertumbuhan cepat, dan menghasilkan daun sawi yang hijau segar serta renyah. Cocok ditanam di dataran rendah maupun tinggi, baik di lahan terbuka, pekarangan rumah, maupun sistem hidroponik.\r\n\r\nBibit sawi ini mudah dalam perawatan, tahan terhadap perubahan cuaca, dan dapat dipanen dalam waktu relatif singkat, sekitar 25–35 hari setelah tanam. Sangat cocok untuk petani pemula maupun berpengalaman yang menginginkan hasil panen berkualitas dan seragam.",
                'harga' => 10000,
                'stok' => 49,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit1.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-07 07:27:42',
            ],
            [
                'id_produk' => 10,
                'nama_produk' => 'Bibit Terong',
                'deskripsi' => "Bibit terong unggul merupakan pilihan tepat untuk menghasilkan tanaman terong yang sehat dan produktif. Bibit ini memiliki daya tumbuh tinggi, batang kuat, serta mampu menghasilkan buah terong yang besar, halus, dan berwarna cerah. Cocok ditanam di dataran rendah maupun dataran tinggi dengan berbagai jenis media tanam.\r\n\r\nBibit terong ini relatif mudah dirawat, tahan terhadap perubahan cuaca, dan memiliki masa panen yang cukup cepat, sekitar 60–70 hari setelah tanam. Sangat sesuai untuk petani pemula maupun petani berpengalaman yang menginginkan hasil panen stabil dan berkualitas.",
                'harga' => 11000,
                'stok' => 45,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit2.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-06 23:17:47',
            ],
            [
                'id_produk' => 11,
                'nama_produk' => 'Bibit Terong Hijau',
                'deskripsi' => "Bibit terong bulat hijau adalah pilihan tepat untuk menghasilkan terong dengan bentuk bulat, warna hijau segar, dan cita rasa yang lezat. Bibit ini memiliki daya tumbuh tinggi, tanaman kuat, serta mampu berbuah lebat dan seragam. Cocok ditanam di dataran rendah maupun dataran tinggi dengan perawatan yang relatif mudah.\r\n\r\nBibit terong bulat hijau dapat dipanen sekitar 60–70 hari setelah tanam. Tanaman ini tahan terhadap perubahan cuaca dan cocok dibudidayakan di lahan terbuka, pekarangan rumah, maupun kebun skala usaha.",
                'harga' => 12000,
                'stok' => 39,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit3.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-07 07:27:43',
            ],
            [
                'id_produk' => 12,
                'nama_produk' => 'Bibit Wortel',
                'deskripsi' => "Bibit wortel unggul dirancang untuk menghasilkan tanaman wortel yang sehat dengan umbi lurus, besar, dan berwarna cerah. Bibit ini memiliki daya tumbuh tinggi dan cocok ditanam di dataran tinggi maupun dataran menengah dengan kondisi tanah yang gembur dan subur.\r\n\r\nBibit wortel ini mudah dibudidayakan dan dapat dipanen sekitar 90–100 hari setelah tanam. Hasil panen memiliki tekstur renyah, rasa manis alami, serta kualitas yang baik untuk konsumsi rumah tangga maupun kebutuhan pasar.",
                'harga' => 13000,
                'stok' => 35,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit4.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-06 23:17:46',
            ],
            [
                'id_produk' => 13,
                'nama_produk' => 'Bibit Jagung',
                'deskripsi' => "Bibit jagung unggul merupakan pilihan tepat untuk menghasilkan tanaman jagung yang sehat dan produktif. Bibit ini memiliki daya tumbuh tinggi, batang kuat, serta mampu menghasilkan tongkol jagung yang besar, padat, dan berisi penuh. Cocok ditanam di dataran rendah maupun dataran menengah dengan berbagai kondisi lahan.\r\n\r\nBibit jagung ini mudah dibudidayakan dan dapat dipanen sekitar 90–110 hari setelah tanam, tergantung varietas. Hasil panen memiliki kualitas baik, rasa manis (untuk jagung konsumsi), dan nilai jual yang tinggi. Sangat cocok untuk petani pemula maupun berpengalaman.",
                'harga' => 14000,
                'stok' => 30,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit5.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-06 23:17:45',
            ],
            [
                'id_produk' => 14,
                'nama_produk' => 'Bibit Padi Moro',
                'deskripsi' => "Bibit padi unggul Moro adalah pilihan tepat untuk meningkatkan hasil produksi pertanian padi. Bibit ini memiliki daya tumbuh tinggi, perakaran kuat, serta mampu menghasilkan tanaman padi yang sehat dengan bulir padi yang berisi dan seragam. Cocok ditanam di lahan sawah irigasi maupun tadah hujan.\r\n\r\nBibit padi ini relatif mudah dibudidayakan, tahan terhadap perubahan cuaca, dan memiliki masa panen yang stabil sesuai varietas yang digunakan. Hasil panen berkualitas baik dengan produktivitas tinggi, sehingga cocok untuk petani pemula maupun petani berpengalaman.",
                'harga' => 15000,
                'stok' => 25,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit6.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-06 23:17:46',
            ],
            [
                'id_produk' => 15,
                'nama_produk' => 'Padi Hibrida 989',
                'deskripsi' => "Benih padi 989 merupakan varietas unggul yang dirancang untuk menghasilkan panen padi yang tinggi dan berkualitas. Benih ini memiliki daya kecambah tinggi, pertumbuhan seragam, serta batang yang kuat sehingga tidak mudah rebah. Cocok ditanam pada lahan sawah irigasi maupun tadah hujan dengan pengelolaan yang baik.\r\n\r\nBenih padi 989 dikenal dengan bulir padi yang berisi penuh, ukuran gabah seragam, dan hasil panen yang stabil. Masa tanam hingga panen relatif efisien, sehingga membantu petani mengatur waktu tanam dengan lebih baik dan meningkatkan produktivitas lahan.",
                'harga' => 16000,
                'stok' => 19,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit7.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-07 07:27:29',
            ],
            [
                'id_produk' => 16,
                'nama_produk' => 'Melon Bintang Asia',
                'deskripsi' => "Benih melon Bintang Asia Hijau merupakan varietas unggul yang menghasilkan buah melon dengan kulit hijau segar dan daging buah manis serta beraroma harum. Benih ini memiliki daya tumbuh tinggi, tanaman kuat, dan produktif, sehingga cocok untuk budidaya di dataran rendah maupun menengah.\r\n\r\nMelon Bintang Asia Hijau memiliki bentuk buah bulat dengan ukuran seragam dan bobot yang baik. Masa panen relatif cepat, sekitar 60–70 hari setelah tanam, dengan kualitas buah yang cocok untuk konsumsi segar maupun pasar komersial.",
                'harga' => 17000,
                'stok' => 15,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit8.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-06 23:17:40',
            ],
            [
                'id_produk' => 17,
                'nama_produk' => 'Melon F1 Luna',
                'deskripsi' => "Benih melon F1 Luna Kuning merupakan varietas hibrida unggul yang menghasilkan buah melon berwarna kuning cerah dengan rasa manis dan daging buah yang tebal. Benih ini memiliki daya tumbuh tinggi, tanaman kuat, serta produktivitas yang baik, sehingga cocok dibudidayakan di dataran rendah maupun menengah.\r\n\r\nMelon F1 Luna Kuning memiliki bentuk buah bulat dengan ukuran seragam dan tampilan menarik. Masa panen relatif cepat, sekitar 60–70 hari setelah tanam. Kualitas buah sangat baik untuk konsumsi segar maupun kebutuhan pasar karena rasa manisnya yang stabil dan tekstur daging buah yang renyah.",
                'harga' => 18000,
                'stok' => 10,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit9.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-06 23:17:39',
            ],
            [
                'id_produk' => 18,
                'nama_produk' => 'Bibit Kacang Panjang',
                'deskripsi' => "Benih kacang panjang hijau merupakan pilihan tepat untuk menghasilkan tanaman kacang panjang yang sehat dan produktif. Benih ini memiliki daya tumbuh tinggi, tanaman merambat yang kuat, serta mampu menghasilkan polong panjang berwarna hijau segar dengan kualitas baik.\r\n\r\nKacang panjang hijau mudah dibudidayakan dan dapat dipanen sekitar 45–55 hari setelah tanam. Tanaman ini cocok ditanam di dataran rendah maupun dataran menengah, baik di lahan terbuka maupun pekarangan rumah.",
                'harga' => 19000,
                'stok' => 5,
                'kategori' => 'Bibit tanaman',
                'gambar_produk' => 'bibit10.jpg',
                'created_at' => '2026-01-07 06:06:49',
                'updated_at' => '2026-01-06 23:17:41',
            ],
        ];

        DB::table('products')->insert($products);
    }
}